package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/evecus/homeproxy-go/internal/config"
	"github.com/evecus/homeproxy-go/internal/resources"
)

// DNSMasq writes dnsmasq nftset fragments for GFW domains.
// Requires dnsmasq with nftset support and nft table inet homeproxy sets gfw_v4/gfw_v6.
type DNSMasq struct {
	Cfg *config.Config
}

func NewDNSMasq(cfg *config.Config) *DNSMasq {
	return &DNSMasq{Cfg: cfg}
}

// WriteGFWConf generates conf with nftset= lines from gfw_list.txt.
func (d *DNSMasq) WriteGFWConf() (string, int, error) {
	cfg := d.Cfg
	if !cfg.DNSMasq.Enabled {
		return "", 0, nil
	}
	path := cfg.DNSMasq.ConfPath
	if path == "" {
		path = "/etc/dnsmasq.d/homeproxy-gfw.conf"
	}
	rm := resources.NewManager(cfg)
	domains, err := rm.LoadGFWList()
	if err != nil {
		return path, 0, fmt.Errorf("load gfw list: %w (run update-resources first)", err)
	}
	maxN := cfg.DNSMasq.MaxDomains
	if maxN <= 0 {
		maxN = 8000
	}
	if len(domains) > maxN {
		domains = domains[:maxN]
	}

	table := cfg.DNSMasq.Table
	if table == "" {
		table = "homeproxy"
	}
	set4 := cfg.DNSMasq.SetV4
	if set4 == "" {
		set4 = "gfw_v4"
	}
	set6 := cfg.DNSMasq.SetV6
	if set6 == "" {
		set6 = "gfw_v6"
	}

	var b strings.Builder
	b.WriteString("# Generated by homeproxy-go — do not edit\n")
	b.WriteString("# nftset: resolved IPs are added to nftables sets for transparent proxy\n")
	b.WriteString("# Requires: dnsmasq nftset support + table inet " + table + "\n\n")

	for _, dom := range domains {
		dom = strings.TrimSpace(dom)
		dom = strings.TrimPrefix(dom, ".")
		if dom == "" || strings.ContainsAny(dom, " \t/") {
			continue
		}
		// family#table#set — table is name only under inet
		b.WriteString(fmt.Sprintf("nftset=/%s/4#inet#%s#%s\n", dom, table, set4))
		if cfg.Proxy.IPv6 {
			b.WriteString(fmt.Sprintf("nftset=/%s/6#inet#%s#%s\n", dom, table, set6))
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return path, 0, err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return path, 0, err
	}
	if err := os.Rename(tmp, path); err != nil {
		return path, 0, err
	}
	return path, len(domains), nil
}
