package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/evecus/homeproxy-go/internal/config"
)

type Nftables struct {
	Cfg       *config.Config
	ChinaIP4  []string
	ChinaIP6  []string
	TableName string
}

func NewNftables(cfg *config.Config, chinaIP4, chinaIP6 []string) *Nftables {
	return &Nftables{Cfg: cfg, ChinaIP4: chinaIP4, ChinaIP6: chinaIP6, TableName: "homeproxy"}
}

func (n *Nftables) Write(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(n.Render()), 0o644)
}

func (n *Nftables) Render() string {
	cfg := n.Cfg
	var b strings.Builder
	b.WriteString("#!/usr/sbin/nft -f\n# Generated by homeproxy-go\n\n")
	b.WriteString(fmt.Sprintf("table inet %s\ndelete table inet %s\n\ntable inet %s {\n", n.TableName, n.TableName, n.TableName))
	n.writeSets(&b)
	n.writeDNSHijack(&b)
	switch cfg.Proxy.Mode {
	case config.ProxyTProxy:
		n.writeTProxy(&b)
	case config.ProxyRedirect:
		n.writeRedirect(&b)
	}
	b.WriteString("}\n")
	return b.String()
}

func (n *Nftables) writeSets(b *strings.Builder) {
	cfg := n.Cfg
	b.WriteString("  set mainland_v4 {\n    type ipv4_addr\n    flags interval\n    auto-merge\n")
	if len(n.ChinaIP4) > 0 {
		b.WriteString("    elements = {\n")
		for _, cidr := range n.ChinaIP4 {
			cidr = strings.TrimSpace(cidr)
			if cidr == "" || strings.HasPrefix(cidr, "#") {
				continue
			}
			b.WriteString("      " + cidr + ",\n")
		}
		b.WriteString("    }\n")
	}
	b.WriteString("  }\n\n")
	if cfg.Proxy.IPv6 {
		b.WriteString("  set mainland_v6 {\n    type ipv6_addr\n    flags interval\n    auto-merge\n")
		if len(n.ChinaIP6) > 0 {
			b.WriteString("    elements = {\n")
			for _, cidr := range n.ChinaIP6 {
				cidr = strings.TrimSpace(cidr)
				if cidr == "" || strings.HasPrefix(cidr, "#") {
					continue
				}
				b.WriteString("      " + cidr + ",\n")
			}
			b.WriteString("    }\n")
		}
		b.WriteString("  }\n\n")
	}
	b.WriteString("  set gfw_v4 {\n    type ipv4_addr\n    flags interval, timeout\n    auto-merge\n  }\n\n")
	n.writeAddrSet(b, "wan_direct_v4", "ipv4_addr", cfg.Control.WANDirectIPv4)
	n.writeAddrSet(b, "wan_proxy_v4", "ipv4_addr", cfg.Control.WANProxyIPv4)
	n.writeAddrSet(b, "lan_direct_v4", "ipv4_addr", cfg.Control.LANDirectIPv4)
	n.writeAddrSet(b, "lan_proxy_v4", "ipv4_addr", cfg.Control.LANProxyIPv4)
}

func (n *Nftables) writeAddrSet(b *strings.Builder, name, typ string, elements []string) {
	b.WriteString(fmt.Sprintf("  set %s {\n    type %s\n    flags interval\n    auto-merge\n", name, typ))
	if len(elements) > 0 {
		b.WriteString("    elements = { " + strings.Join(elements, ", ") + " }\n")
	}
	b.WriteString("  }\n\n")
}

func (n *Nftables) iifMatch() string {
	ifaces := n.Cfg.Control.LANInterfaces
	if len(ifaces) == 0 {
		return ""
	}
	quoted := make([]string, len(ifaces))
	for i, iface := range ifaces {
		quoted[i] = `"` + iface + `"`
	}
	return "iifname { " + strings.Join(quoted, ", ") + " } "
}

func (n *Nftables) writeDNSHijack(b *strings.Builder) {
	iif := n.iifMatch()
	b.WriteString("  chain dstnat_dns {\n    type nat hook prerouting priority dstnat - 10; policy accept;\n")
	b.WriteString(fmt.Sprintf("    %smeta l4proto { udp, tcp } th dport 53 counter redirect to :%d\n  }\n\n", iif, n.Cfg.DNS.ListenPort))
}

func (n *Nftables) writeTProxy(b *strings.Builder) {
	cfg := n.Cfg
	mark := config.NormalizeMark(cfg.Proxy.TProxyMark)
	port := cfg.Proxy.TProxyPort
	iif := n.iifMatch()
	b.WriteString("  chain mangle_prerouting {\n    type filter hook prerouting priority mangle; policy accept;\n")
	b.WriteString(fmt.Sprintf("    %smeta l4proto { tcp, udp } jump hp_tproxy_lan\n  }\n\n", iif))
	b.WriteString("  chain hp_tproxy_lan {\n    fib daddr type local return\n")
	b.WriteString("    ip daddr { 0.0.0.0/8, 10.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255 } return\n")
	b.WriteString("    ip saddr @lan_direct_v4 return\n    ip daddr @wan_direct_v4 return\n")
	switch cfg.Mode {
	case config.ModeBypassMainlandChina:
		b.WriteString("    ip daddr @mainland_v4 return\n")
	case config.ModeProxyMainlandChina:
		b.WriteString("    ip daddr != @mainland_v4 return\n")
	case config.ModeGFWList:
		b.WriteString("    ip daddr != @gfw_v4 return\n")
	}
	b.WriteString("    goto hp_do_tproxy\n  }\n\n")
	b.WriteString("  chain hp_do_tproxy {\n")
	b.WriteString(fmt.Sprintf("    meta l4proto { tcp, udp } meta mark set %s tproxy to :%d accept\n  }\n\n", mark, port))
	b.WriteString("  chain mangle_output {\n    type route hook output priority mangle; policy accept;\n")
	b.WriteString(fmt.Sprintf("    meta mark %s accept\n    meta l4proto { tcp, udp } jump hp_tproxy_output\n  }\n\n", config.NormalizeMark(cfg.Proxy.SelfMark)))
	b.WriteString("  chain hp_tproxy_output {\n    fib daddr type local return\n")
	b.WriteString("    ip daddr { 0.0.0.0/8, 10.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255 } return\n")
	if cfg.Mode == config.ModeBypassMainlandChina || cfg.Control.BypassCNTraffic {
		b.WriteString("    ip daddr @mainland_v4 return\n")
	}
	b.WriteString(fmt.Sprintf("    meta l4proto { tcp, udp } meta mark set %s\n  }\n\n", mark))
}

func (n *Nftables) writeRedirect(b *strings.Builder) {
	cfg := n.Cfg
	port := cfg.Proxy.RedirectPort
	iif := n.iifMatch()
	b.WriteString("  chain dstnat_redir {\n    type nat hook prerouting priority dstnat; policy accept;\n")
	b.WriteString(fmt.Sprintf("    %smeta l4proto tcp jump hp_redirect_lan\n  }\n\n", iif))
	b.WriteString("  chain hp_redirect_lan {\n    fib daddr type local return\n")
	b.WriteString("    ip daddr { 0.0.0.0/8, 10.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255 } return\n")
	b.WriteString("    ip saddr @lan_direct_v4 return\n    ip daddr @wan_direct_v4 return\n")
	switch cfg.Mode {
	case config.ModeBypassMainlandChina:
		b.WriteString("    ip daddr @mainland_v4 return\n")
	case config.ModeProxyMainlandChina:
		b.WriteString("    ip daddr != @mainland_v4 return\n")
	case config.ModeGFWList:
		b.WriteString("    ip daddr != @gfw_v4 return\n")
	}
	b.WriteString(fmt.Sprintf("    meta l4proto tcp redirect to :%d\n  }\n\n", port))
}
