package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/evecus/homeproxy-go/internal/config"
)

// Nftables generates nft rules for transparent proxy + China IP / ACL sets.
type Nftables struct {
	Cfg       *config.Config
	ChinaIP4  []string
	ChinaIP6  []string
	TableName string
}

func NewNftables(cfg *config.Config, chinaIP4, chinaIP6 []string) *Nftables {
	return &Nftables{
		Cfg:       cfg,
		ChinaIP4:  chinaIP4,
		ChinaIP6:  chinaIP6,
		TableName: "homeproxy",
	}
}

func (n *Nftables) Write(path string) error {
	content := n.Render()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func (n *Nftables) Render() string {
	cfg := n.Cfg
	var b strings.Builder

	b.WriteString("#!/usr/sbin/nft -f\n")
	b.WriteString("# Generated by homeproxy-go — do not edit by hand\n\n")
	b.WriteString(fmt.Sprintf("table inet %s\n", n.TableName))
	b.WriteString(fmt.Sprintf("delete table inet %s\n\n", n.TableName))
	b.WriteString(fmt.Sprintf("table inet %s {\n", n.TableName))

	// --- sets ---
	n.writeSets(&b)

	// --- chains ---
	n.writeDNSHijack(&b)
	switch cfg.Proxy.Mode {
	case config.ProxyTProxy:
		n.writeTProxy(&b)
	case config.ProxyRedirect:
		n.writeRedirect(&b)
	case config.ProxyTUN:
		// TUN: typically no redirect; routing handled by tun device + policy
		b.WriteString("  # TUN mode: traffic enters via tun interface; no tproxy/redirect chains\n")
	}

	b.WriteString("}\n")
	return b.String()
}

func (n *Nftables) writeSets(b *strings.Builder) {
	cfg := n.Cfg

	// China IPv4
	b.WriteString("  set mainland_v4 {\n")
	b.WriteString("    type ipv4_addr\n")
	b.WriteString("    flags interval\n")
	b.WriteString("    auto-merge\n")
	if len(n.ChinaIP4) > 0 {
		b.WriteString("    elements = {\n")
		for _, cidr := range n.ChinaIP4 {
			cidr = strings.TrimSpace(cidr)
			if cidr == "" || strings.HasPrefix(cidr, "#") {
				continue
			}
			b.WriteString("      " + cidr + ",\n")
		}
		b.WriteString("    }\n")
	}
	b.WriteString("  }\n\n")

	if cfg.Proxy.IPv6 {
		b.WriteString("  set mainland_v6 {\n")
		b.WriteString("    type ipv6_addr\n")
		b.WriteString("    flags interval\n")
		b.WriteString("    auto-merge\n")
		if len(n.ChinaIP6) > 0 {
			b.WriteString("    elements = {\n")
			for _, cidr := range n.ChinaIP6 {
				cidr = strings.TrimSpace(cidr)
				if cidr == "" || strings.HasPrefix(cidr, "#") {
					continue
				}
				b.WriteString("      " + cidr + ",\n")
			}
			b.WriteString("    }\n")
		}
		b.WriteString("  }\n\n")
	}

	// GFW dynamic set — filled by dnsmasq nftset= when DNSMasq.Enabled
	b.WriteString("  set gfw_v4 {\n")
	b.WriteString("    type ipv4_addr\n")
	b.WriteString("    flags timeout\n")
	b.WriteString("    timeout 1h\n")
	b.WriteString("  }\n\n")
	if cfg.Proxy.IPv6 {
		b.WriteString("  set gfw_v6 {\n")
		b.WriteString("    type ipv6_addr\n")
		b.WriteString("    flags timeout\n")
		b.WriteString("    timeout 1h\n")
		b.WriteString("  }\n\n")
	}

	// WAN ACL
	n.writeAddrSet(b, "wan_direct_v4", "ipv4_addr", cfg.Control.WANDirectIPv4)
	n.writeAddrSet(b, "wan_proxy_v4", "ipv4_addr", cfg.Control.WANProxyIPv4)
	if cfg.Proxy.IPv6 {
		n.writeAddrSet(b, "wan_direct_v6", "ipv6_addr", cfg.Control.WANDirectIPv6)
		n.writeAddrSet(b, "wan_proxy_v6", "ipv6_addr", cfg.Control.WANProxyIPv6)
	}
	n.writeAddrSet(b, "lan_direct_v4", "ipv4_addr", cfg.Control.LANDirectIPv4)
	n.writeAddrSet(b, "lan_proxy_v4", "ipv4_addr", cfg.Control.LANProxyIPv4)
	if cfg.Proxy.IPv6 {
		n.writeAddrSet(b, "lan_direct_v6", "ipv6_addr", cfg.Control.LANDirectIPv6)
		n.writeAddrSet(b, "lan_proxy_v6", "ipv6_addr", cfg.Control.LANProxyIPv6)
	}

	if cfg.Control.RoutingPorts != "" {
		b.WriteString("  set routing_port {\n")
		b.WriteString("    type inet_service\n")
		b.WriteString("    flags interval\n")
		b.WriteString("    auto-merge\n")
		b.WriteString("    elements = { " + cfg.Control.RoutingPorts + " }\n")
		b.WriteString("  }\n\n")
	}
}

func (n *Nftables) writeAddrSet(b *strings.Builder, name, typ string, elements []string) {
	b.WriteString(fmt.Sprintf("  set %s {\n", name))
	b.WriteString(fmt.Sprintf("    type %s\n", typ))
	b.WriteString("    flags interval\n")
	b.WriteString("    auto-merge\n")
	if len(elements) > 0 {
		b.WriteString("    elements = { " + strings.Join(elements, ", ") + " }\n")
	}
	b.WriteString("  }\n\n")
}

func (n *Nftables) iifMatch() string {
	ifaces := n.Cfg.Control.LANInterfaces
	if len(ifaces) == 0 {
		return ""
	}
	quoted := make([]string, len(ifaces))
	for i, iface := range ifaces {
		quoted[i] = `"` + iface + `"`
	}
	return "iifname { " + strings.Join(quoted, ", ") + " } "
}

func (n *Nftables) writeDNSHijack(b *strings.Builder) {
	cfg := n.Cfg
	iif := n.iifMatch()
	b.WriteString("  chain dstnat_dns {\n")
	b.WriteString("    type nat hook prerouting priority dstnat - 10; policy accept;\n")
	b.WriteString(fmt.Sprintf("    %smeta l4proto { udp, tcp } th dport 53 counter redirect to :%d comment \"homeproxy dns hijack\"\n", iif, cfg.DNS.ListenPort))
	b.WriteString("  }\n\n")
}

func (n *Nftables) writeTProxy(b *strings.Builder) {
	cfg := n.Cfg
	mark := config.NormalizeMark(cfg.Proxy.TProxyMark)
	port := cfg.Proxy.TProxyPort
	iif := n.iifMatch()

	// prerouting mangle: mark + tproxy
	b.WriteString("  chain mangle_prerouting {\n")
	b.WriteString("    type filter hook prerouting priority mangle; policy accept;\n")
	b.WriteString(fmt.Sprintf("    %smeta l4proto { tcp, udp } jump hp_tproxy_lan\n", iif))
	b.WriteString("  }\n\n")

	b.WriteString("  chain hp_tproxy_lan {\n")
	// local / reserved
	b.WriteString("    fib daddr type local return\n")
	b.WriteString("    ip daddr { 0.0.0.0/8, 10.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255 } return\n")
	if cfg.Proxy.IPv6 {
		b.WriteString("    ip6 daddr { ::/128, ::1/128, fc00::/7, fe80::/10, ff00::/8 } return\n")
	}

	// Gaming mode: always direct
	for _, ip := range cfg.Control.LANGamingIPv4 {
		if ip = strings.TrimSpace(ip); ip != "" {
			b.WriteString(fmt.Sprintf("    ip saddr %s return\n", ip))
		}
	}
	if cfg.Proxy.IPv6 {
		for _, ip := range cfg.Control.LANGamingIPv6 {
			if ip = strings.TrimSpace(ip); ip != "" {
				b.WriteString(fmt.Sprintf("    ip6 saddr %s return\n", ip))
			}
		}
	}
	for _, mac := range cfg.Control.LANGamingMAC {
		if mac = strings.TrimSpace(mac); mac != "" {
			b.WriteString(fmt.Sprintf("    ether saddr %s return\n", mac))
		}
	}
	// Global proxy devices: force tproxy
	for _, ip := range cfg.Control.LANGlobalProxyIPv4 {
		if ip = strings.TrimSpace(ip); ip != "" {
			b.WriteString(fmt.Sprintf("    ip saddr %s goto hp_do_tproxy\n", ip))
		}
	}
	if cfg.Proxy.IPv6 {
		for _, ip := range cfg.Control.LANGlobalProxyIPv6 {
			if ip = strings.TrimSpace(ip); ip != "" {
				b.WriteString(fmt.Sprintf("    ip6 saddr %s goto hp_do_tproxy\n", ip))
			}
		}
	}
	for _, mac := range cfg.Control.LANGlobalProxyMAC {
		if mac = strings.TrimSpace(mac); mac != "" {
			b.WriteString(fmt.Sprintf("    ether saddr %s goto hp_do_tproxy\n", mac))
		}
	}

	// LAN ACL (homeproxy-style lan_proxy_mode)
	switch cfg.Control.LANProxyMode {
	case config.LANProxyExceptListed:
		b.WriteString("    ip saddr @lan_direct_v4 return\n")
		if cfg.Proxy.IPv6 {
			b.WriteString("    ip6 saddr @lan_direct_v6 return\n")
		}
		for _, mac := range cfg.Control.LANDirectMAC {
			mac = strings.TrimSpace(mac)
			if mac != "" {
				b.WriteString(fmt.Sprintf("    ether saddr %s return\n", mac))
			}
		}
	case config.LANProxyListedOnly:
		if len(cfg.Control.LANProxyIPv4) > 0 {
			b.WriteString("    ip saddr != @lan_proxy_v4 return\n")
		}
		if cfg.Proxy.IPv6 && len(cfg.Control.LANProxyIPv6) > 0 {
			b.WriteString("    ip6 saddr != @lan_proxy_v6 return\n")
		}
		macs := make([]string, 0)
		for _, mac := range cfg.Control.LANProxyMAC {
			mac = strings.TrimSpace(mac)
			if mac != "" {
				macs = append(macs, mac)
			}
		}
		if len(macs) > 0 {
			b.WriteString("    ether saddr != { " + strings.Join(macs, ", ") + " } return\n")
		}
	default:
		b.WriteString("    ip saddr @lan_direct_v4 return\n")
		if cfg.Proxy.IPv6 {
			b.WriteString("    ip6 saddr @lan_direct_v6 return\n")
		}
	}

	// WAN direct destinations
	b.WriteString("    ip daddr @wan_direct_v4 return\n")
	if cfg.Proxy.IPv6 {
		b.WriteString("    ip6 daddr @wan_direct_v6 return\n")
	}

	// Mode-specific destination filtering
	switch cfg.Mode {
	case config.ModeBypassMainlandChina:
		b.WriteString("    ip daddr @mainland_v4 return\n")
		if cfg.Proxy.IPv6 {
			b.WriteString("    ip6 daddr @mainland_v6 return\n")
		}
	case config.ModeProxyMainlandChina:
		b.WriteString("    ip daddr != @mainland_v4 return\n")
		if cfg.Proxy.IPv6 {
			b.WriteString("    ip6 daddr != @mainland_v6 return\n")
		}
	case config.ModeGFWList:
		b.WriteString("    ip daddr != @gfw_v4 return\n")
		if cfg.Proxy.IPv6 {
			b.WriteString("    ip6 daddr != @gfw_v6 return\n")
		}
	}

	if cfg.Control.RoutingPorts != "" {
		b.WriteString("    meta l4proto { tcp, udp } th dport != @routing_port return\n")
	}

	b.WriteString("    ip daddr @wan_proxy_v4 goto hp_do_tproxy\n")
	if cfg.Proxy.IPv6 {
		b.WriteString("    ip6 daddr @wan_proxy_v6 goto hp_do_tproxy\n")
	}

	b.WriteString("    goto hp_do_tproxy\n")
	b.WriteString("  }\n\n")

	b.WriteString("  chain hp_do_tproxy {\n")
	b.WriteString(fmt.Sprintf("    meta l4proto { tcp, udp } meta mark set %s tproxy to :%d accept\n", mark, port))
	b.WriteString("  }\n\n")

	// output chain for router-originated traffic (optional)
	b.WriteString("  chain mangle_output {\n")
	b.WriteString("    type route hook output priority mangle; policy accept;\n")
	b.WriteString(fmt.Sprintf("    meta mark %s accept\n", config.NormalizeMark(cfg.Proxy.SelfMark)))
	b.WriteString("    meta l4proto { tcp, udp } jump hp_tproxy_output\n")
	b.WriteString("  }\n\n")

	b.WriteString("  chain hp_tproxy_output {\n")
	b.WriteString("    fib daddr type local return\n")
	b.WriteString("    ip daddr { 0.0.0.0/8, 10.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255 } return\n")
	if cfg.Mode == config.ModeBypassMainlandChina || cfg.Control.BypassCNTraffic {
		b.WriteString("    ip daddr @mainland_v4 return\n")
		if cfg.Proxy.IPv6 {
			b.WriteString("    ip6 daddr @mainland_v6 return\n")
		}
	}
	b.WriteString(fmt.Sprintf("    meta l4proto { tcp, udp } meta mark set %s\n", mark))
	b.WriteString("  }\n\n")

	// Policy routing helper comment
	b.WriteString(fmt.Sprintf("  # Required: ip rule add fwmark %s lookup 100\n", mark))
	b.WriteString("  # Required: ip route add local default dev lo table 100\n")
}

func (n *Nftables) writeRedirect(b *strings.Builder) {
	cfg := n.Cfg
	port := cfg.Proxy.RedirectPort
	iif := n.iifMatch()

	b.WriteString("  chain dstnat_redir {\n")
	b.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n")
	b.WriteString(fmt.Sprintf("    %smeta l4proto tcp jump hp_redirect_lan\n", iif))
	b.WriteString("  }\n\n")

	b.WriteString("  chain hp_redirect_lan {\n")
	b.WriteString("    fib daddr type local return\n")
	b.WriteString("    ip daddr { 0.0.0.0/8, 10.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255 } return\n")
	b.WriteString("    ip saddr @lan_direct_v4 return\n")
	b.WriteString("    ip daddr @wan_direct_v4 return\n")

	switch cfg.Mode {
	case config.ModeBypassMainlandChina:
		b.WriteString("    ip daddr @mainland_v4 return\n")
	case config.ModeProxyMainlandChina:
		b.WriteString("    ip daddr != @mainland_v4 return\n")
	case config.ModeGFWList:
		b.WriteString("    ip daddr != @gfw_v4 return\n")
	}

	if cfg.Control.RoutingPorts != "" {
		b.WriteString("    tcp dport != @routing_port return\n")
	}
	b.WriteString(fmt.Sprintf("    meta l4proto tcp redirect to :%d\n", port))
	b.WriteString("  }\n\n")
}
